INSERT INTO `menu_list` VALUES (1, '首页');
INSERT INTO `menu_list` VALUES (2, '3.2上新季');
INSERT INTO `menu_list` VALUES (3, '唯品国际');
INSERT INTO `menu_list` VALUES (4, '母婴');
INSERT INTO `menu_list` VALUES (7, '居家');
INSERT INTO `menu_list` VALUES (8, '男士');
INSERT INTO `menu_list` VALUES (9, '美妆');
INSERT INTO `menu_list` VALUES (10, '生活');
INSERT INTO `menu_list` VALUES (11, '更多');
